//
// Contact.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class Contact: JSONEncodable {
    public var id: Int64?
    public var name: String?
    public var jobTitle: String?
    public var phone: String?
    public var email: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Id"] = self.id?.encodeToJSON()
        nillableDictionary["Name"] = self.name
        nillableDictionary["JobTitle"] = self.jobTitle
        nillableDictionary["Phone"] = self.phone
        nillableDictionary["Email"] = self.email
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
